layout_spectrum: 0.1523297
typography_spectrum: 0.4247312
color:
  saturation: 0.1813226
  lightness: 0.6290506
  brandStrength: 0.2329749
  rhythmicContrast: 0.2240143
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: j•ess
